server:
  port: 8080

spring:
  application:
    name: conduitedeprojet
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://database:5432/conduitedeprojet_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:changeme}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000} # 1 hour in ms

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${API_DOCS_ENABLED:false}
