server:
  port: 8080

spring:
  application:
    name: conduitedeprojet
  datasource:
    url: jdbc:postgresql://database:5432/conduitedeprojet_db
    username: admin
    password: admin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: 5St66hi6E8M7oRbgHLpZT/VZgErpyKQXZMhUtAfHr6Y= # Only for development
    expiration-ms: 3600000 # 1 hour in ms

app:
  frontend:
    url: http://localhost:5173
