name: Backend tests

on:
  workflow_call:

permissions: write-all

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Run backend formatting check
        working-directory: ./backend
        run: mvn spotless:check

      - name: Run backend tests
        working-directory: ./backend
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload backend test reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: |
            backend/target/surefire-reports

      - name: Upload backend test coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-coverage-reports
          path: |
            backend/target/site/jacoco
